name: CI

on: [push, pull_request]

jobs:
  windows:
    strategy:
      matrix:
        arch: [32, 64]
        include:
          - arch: 32
            cmake_arch: "Win32"
            llvm_url: http://releases.llvm.org/9.0.0/LLVM-9.0.0-win32.exe
          - arch: 64
            cmake_arch: "x64"
            llvm_url: http://releases.llvm.org/9.0.0/LLVM-9.0.0-win64.exe
    runs-on: windows-2019
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v1
    - name: "LLVM "
      shell: bash
      run: |
        curl -kL "${{ matrix.llvm_url }}" -f --retry 5 -o llvm.exe
        7z -oLLVM x llvm.exe
        echo "::set-env PATH=$CD;$PATH"
    - name: "WebRTC Dependency"
      shell: bash
      run: |
        curl -kL "https://github.com/caffeinetv/webrtc/releases/download/v70.2-libcaffeine/webrtc-prebuilt-windows.7z" -f --retry 5 -o webrtc.7z
        7z -owebrtc x webrtc.7z
      with:
        path: ${}
    - name: "Configure"
      shell: bash
      run: cmake -H. -Bbuild -G "Visual Studio 16 2019" -A${{ matrix.cmake_arch }} -T"LLVM" -DWEBRTC_ROOT_DIR=webrtc
    - name: "Build"
      shell: bash
      run: cmake --build build --config RelWithDebInfo
